services:
  - type: web
    name: english-talking-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn english_bot:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: TELEGRAM_TOKEN
      - key: WEBHOOK_SECRET_PATH
      - key: TELEGRAM_WEBHOOK_SECRET_TOKEN
      - key: PUBLIC_URL
      - key: OPENAI_API_KEY
    plan: Professional
